### ISSUE TITLE
databaseDetails not specified

### ISSUE THREAD

**Issue by rossdwilliams** [ohdsi-studies/OLGLMM-COVID#1]
in the example: https://github.com/ohdsi-studies/OLGLMM-COVID/blob/master/PROSPECTIVE-EXECUTE.md

the databaseDetails are not specified

I assume as in the 2nd section it is

databaseDetails <- PatientLevelPrediction::createDatabaseDetails(
  connectionDetails = connectionDetails, 
  cdmDatabaseSchema = cdmDatabaseSchema, 
  cdmDatabaseName = cdmDatabaseSchema,
  tempEmulationSchema = tempEmulationSchema,
  cohortDatabaseSchema = cohortDatabaseSchema,
  cohortTable = cohortTable,
  outcomeDatabaseSchema = cohortDatabaseSchema,
  outcomeTable = cohortTable,
  cdmVersion = 5
)

**Comment by jreps** [comment]
yes - I updated the readme to fix it :)
